feat: Toggle drop sync server setting
tiltedphoques/TiltedEvolution pull request #253
Opened 2022-07-11 11:12 UTC by Merlin6019

2022-07-11 12:12 UTC, croscas commented
Can you update the description of the PR with meaningful information? For example what problem is it solving, the changes required in the codebase and how have you tested that this change works as expected.

2022-07-11 12:12 UTC, RobbeBryssinck commented
The idea is good, but there are some implementation problems. This is rather overkill. We're sending the option to the client here, but that seems unnecessary. The client doesn't really have to do anything for this behavior to function. Furthermore, we don't really need to store it in ServerSettings in this case. It can just stand on its own. Look at fGoldLossFactor for a better example.

2022-07-11 14:43 UTC, RobbeBryssinck commented on Code/server/Services/InventoryService.cpp
> +#include <client/World.cpp>
Same thing, don't include cpp.

2022-07-12 11:21 UTC, yamashi requested changes

2022-07-12 11:21 UTC, yamashi commented on Code/server/Services/InventoryService.cpp
> +    if (bEnableItemDrops)
These 4 lines could just be

notify.Drop = bEnableItemDrops ? message.Drop : false;

2022-07-31 09:37 UTC, merged