Scroll through sent chat messages with the arrow keys
tiltedphoques/TiltedEvolution pull request #345
Opened 2022-07-16 21:32 UTC by Sturlen

Use the up and down arrows to scroll through your sent chat messages/commands so you can easily repeat them. Inspired by the functionality in CMD and BASH.

example:
- type in and send message "/tp player"
- hit the up arrow key and enter to send the same command again.

Needs cleaning before it's merged, but I'd like to check in if anyone is working on something similar or for comments before spending too much time on it.

2022-07-16 21:33 UTC, RobbeBryssinck commented
I'll ask Dragonisser to review for you

2022-07-16 21:51 UTC, Dragonisser commented
Few things.

1. Might wanna limit the history to a certain size and do round-robin (E.g. only keep the last 50 messages, delete the first and append the new one)
2. No one works on it as of now even though it was internally discussed already
3. Has this been tested ingame?

2022-07-16 22:00 UTC, Sturlen commented
Putting limits on history is probably a good idea.
Only been tested in the browser yet, but ingame testing is next on the todo list.

2022-07-22 09:25 UTC, Sturlen commented
Tested in game, and both chat messages and commands work as intended.

2022-07-25 09:32 UTC, Dragonisser requested changes
Please change that part mentioned or comment why it wouldnt work. Then it can be merged.

2022-07-25 10:19 UTC, Sturlen commented on Code/skyrim_ui/src/app/components/chat/message-history.ts
> +    const isNewMessageDifferent = newMsg != this.stack[this.offset];
I think it makes the code more readable, but that's just my preference. Variable has been removed.

2022-07-25 10:20 UTC, Dragonisser approved these changes
Can be merged.

2022-07-25 11:43 UTC, merged