Add server command for setting TimeScale
tiltedphoques/TiltedEvolution pull request #427
Opened 2022-07-28 20:42 UTC by Sturlen

Let you set how fast time passes on the server. 
- 0 will stop the clock
- 1 will move at realtime
- 1000 set it to 50x skyrim's normal speed

Tested in game with two clients. Left on for an hour at 1000 timescale with no noticable effects, other than water moving animating way too fast.

https://user-images.githubusercontent.com/43607012/181633426-df0830c2-1ecd-42a8-8d2e-427f227efd37.mp4

2022-07-29 03:06 UTC, invaderdimz commented
Make sure this is even viable because Time Scale might mess up some quests. Especially ones that go off time. I'm assuming this because in Fallout New Vegas ik adjusting time scale will break some quests.

2022-07-29 07:15 UTC, RobbeBryssinck commented
I don't see the use of this.

2022-07-29 07:39 UTC, Sturlen commented
> Make sure this is even viable because changing Time Scale might mess up some quests.

I don't recall any quests with timelimits, but it's been a while since I did a full playthrough. If you know of any, let me know and I can test them.

> I don't see the use of this.

It's been requested on the discord quite a lot:
"I wish there was a way to modify the timescale though. You'll never experience half the seasons at the rate it goes"
"Is it possible to tweak the server timescale?"
"how do I change the timescale?"
"can you change the date and timescale when hosting a server?"
and so forth.

 Some people want to see the seasons pass them by and some want time to feel real.

2022-07-29 08:30 UTC, RobbeBryssinck commented
This will most likely have unforeseen gameplay implications. Also, skyrim doesn't have a concept of seasons.

2022-07-29 21:08 UTC, Sturlen commented
> This will most likely have unforeseen gameplay implications.

I do agree that it's currently untested territory and I could add a warning if you want. Still, setting TimeScale on clients is an existing feature and this just lets users access it. If the setting the TimeScale is too unstable to ever be used, then why is it fully implemented and synchronized?

> Also, skyrim doesn't have a concept of seasons.

I should have worded it better.
Was meant as the months of the calandar changing, people want it for immersion reasons.

2022-07-30 20:03 UTC, RobbeBryssinck requested changes
Should make it a server setting then too, not just a command.

2022-07-30 20:03 UTC, RobbeBryssinck commented on Code/server/Services/CalendarService.cpp
> +        GameServer::Get()->SendToLoaded(timeMsg);
Use SendToPlayers()

2022-07-31 09:43 UTC, Sturlen commented on Code/server/Services/CalendarService.cpp
> +        GameServer::Get()->SendToLoaded(timeMsg);
fixed

2022-08-01 16:08 UTC, merged