RU localization files
tiltedphoques/TiltedEvolution pull request #430
Opened 2022-07-29 17:01 UTC by Sidiusz

1. Add the link to the official site, removed the community VK link
2. Fixed Russian and other symbols in the font
3. Added Russian localization file

2022-08-04 15:24 UTC, RobbeBryssinck commented on Code/skyrim_ui/src/app/transloco-root.module.ts
> +		  { id: 'ru', label: 'Русский' },
Indentation

2022-08-04 15:41 UTC, RobbeBryssinck commented
Why the change in font file?

2022-08-05 00:10 UTC, Sidiusz commented
> Why the change in font file?

Cyrillic letters do not have the same style as Latin letters

2022-08-12 14:48 UTC, scomans requested changes

2022-08-12 14:48 UTC, scomans commented on Code/skyrim_ui/src/assets/i18n/ru.json
> +      "MESSAGE_FROM": "Сообщение от "
missing:
```
"ACCEPT": "Accept",
"DECLINE": "Decline",
```

2022-08-12 16:19 UTC, Sidiusz commented on Code/skyrim_ui/src/assets/i18n/ru.json
> +      "DECLINE": "Отклонить"
Added

2022-08-12 18:21 UTC, merged