NL localization files
tiltedphoques/TiltedEvolution pull request #436
Opened 2022-07-30 19:44 UTC by NL-TCH

Added the dutch language+ changed the language list order to an alphabetic order (de before en) 

#sorry deleted my forked repo :(

2022-07-30 19:44 UTC, RobbeBryssinck commented
Merge to dev instead of master.

2022-07-30 19:47 UTC, NL-TCH commented
sorry, will do next time

2022-07-30 19:51 UTC, RobbeBryssinck requested changes

2022-07-30 19:51 UTC, RobbeBryssinck commented on Code/skyrim_ui/src/assets/i18n/nl.json
> +        "HELGEN": "Verbind niet met een server wanneer je nog in de Helgen introductie ben. Zorg ervoor dat je eerst uit Helgen vlugt"
bent*

2022-07-30 19:51 UTC, RobbeBryssinck commented on Code/skyrim_ui/src/assets/i18n/nl.json
> +        "HELGEN": "Verbind niet met een server wanneer je nog in de Helgen introductie ben. Zorg ervoor dat je eerst uit Helgen vlugt"
vlucht*

2022-07-30 19:51 UTC, RobbeBryssinck commented on Code/skyrim_ui/src/assets/i18n/nl.json
> +        "HELGEN": "Verbind niet met een server wanneer je nog in de Helgen introductie ben. Zorg ervoor dat je eerst uit Helgen vlugt"
Punt aan het einde van de zin

2022-07-30 19:51 UTC, RobbeBryssinck commented on Code/skyrim_ui/src/assets/i18n/nl.json
> +      "CANCEL": "Anuleren",
Annuleren

2022-07-30 19:51 UTC, RobbeBryssinck commented on Code/skyrim_ui/src/assets/i18n/nl.json
> +      "PUBLIC_SERVERS": "Publieke servers",
Openbare servers

2022-07-30 19:51 UTC, RobbeBryssinck commented on Code/skyrim_ui/src/assets/i18n/nl.json
> +        "INVALID_ADDRESS": "Het adres is in een niet geldig formaat"
ongeldig ipv niet geldig

2022-07-30 19:51 UTC, RobbeBryssinck commented on Code/skyrim_ui/src/assets/i18n/nl.json
> +        "INVALID_ADDRESS": "Het adres is in een niet geldig formaat."
ongeldig ipv niet geldig

2022-07-30 19:51 UTC, RobbeBryssinck commented on Code/skyrim_ui/src/assets/i18n/nl.json
> +        "PARTY_LEADER_LOOT_QUESTITEMS": "Alleen de groepsleider kan quests elementen looten",
"quest items" ipv "quest elementen"

2022-07-30 19:51 UTC, RobbeBryssinck commented on Code/skyrim_ui/src/assets/i18n/nl.json
> +        "TOP_RIGHT": "TRechtsboven",
Rechtsboven

2022-07-30 19:51 UTC, RobbeBryssinck commented on Code/skyrim_ui/src/assets/i18n/nl.json
> +        "BOTTOM_LEFT": "BLinksonder"
Linksonder

2022-07-30 19:52 UTC, RobbeBryssinck commented
Let op de punten aan het einde van zinnen.

2022-07-30 20:00 UTC, NL-TCH commented
sorry, dat waren hele slordige fouten, bedankt voor het nakeijken en voor het aandragen van verbeterpunten!

2022-08-03 15:19 UTC, golress reviewed
I noticed a few more small mistakes.

2022-08-03 15:19 UTC, golress commented on Code/skyrim_ui/src/app/transloco-root.module.ts
> +          { id: 'fr', label: 'Français'},
Add a space before } for consistency.

2022-08-03 15:19 UTC, golress commented on Code/skyrim_ui/src/assets/i18n/nl.json
> +        "PARTY_LEADER_LOOT_QUESTITEMS": "Alleen de groepsleider kan quests items looten.",
quests -> quest
Also maybe the last few words need to be translated a bit more, something like "quest voorwerpen oprapen"?

2022-08-04 15:34 UTC, merged