UI Refactor: Replace checkbox component with directive
tiltedphoques/TiltedEvolution pull request #443
Opened 2022-08-02 16:10 UTC by Sturlen

Simplifes checkbox code while keeping the great skyrim-y look and checkbox sound. No visible change. Tested in game.

2022-08-02 17:25 UTC, scomans requested changes
Pretty nice!

2022-08-02 17:25 UTC, scomans commented on Code/skyrim_ui/src/app/directives/checkbox.directive.ts
> +    const target: HTMLInputElement = event.target
```suggestion
  onChange(event: Event) {
    const target = event.target as HTMLInputElement;
```

2022-08-02 17:25 UTC, scomans commented on Code/skyrim_ui/src/app/directives/checkbox.directive.ts
> +  ]
Remove: it will create another SoundService instance for every checkbox

2022-08-02 17:25 UTC, scomans commented on Code/skyrim_ui/src/app/components/settings/settings.component.html
> +        <input type="checkbox"
put it in a new line for consistency
```suggestion
        <input 
          type="checkbox"
```

2022-08-02 17:25 UTC, scomans commented on Code/skyrim_ui/src/app/components/settings/settings.component.html
> +        <input type="checkbox"
put it in a new line for consistency
```suggestion
        <input 
          type="checkbox"
```

2022-08-02 17:25 UTC, scomans commented on Code/skyrim_ui/src/app/components/settings/settings.component.html
> +        <input type="checkbox"
put it in a new line for consistency
```suggestion
        <input
          type="checkbox"
```

2022-08-02 17:25 UTC, scomans commented on Code/skyrim_ui/src/app/components/settings/settings.component.html
> +        <input type="checkbox"
put it in a new line for consistency
```suggestion
        <input
          type="checkbox"
```

2022-08-02 17:25 UTC, scomans commented on Code/skyrim_ui/src/app/components/server-list/server-list.component.html
> +      <input type="checkbox"
put it in a new line for consistency
```suggestion
      <input
        type="checkbox"
```

2022-08-02 17:25 UTC, scomans commented on Code/skyrim_ui/src/app/components/connect/connect.component.html
> +    <input type="checkbox"
put it in a new line for consistency
```suggestion
    <input
      type="checkbox"
```

2022-08-02 17:25 UTC, scomans commented on Code/skyrim_ui/src/app/app.module.ts
> +    CheckboxDirective
put it at the top of the directive list for alphabetical order

2022-08-04 13:17 UTC, Sturlen commented
@scomans All requested changes have been made

2022-08-04 14:00 UTC, scomans commented
I'm just a contributor so I can't merge or resolve anything 😅 Request a review from @Dragonisser for that

2022-08-04 14:30 UTC, Sturlen commented
Oh sorry, didn't realise.  Thanks for letting me know 👍

2022-08-04 15:38 UTC, merged