Create pl.json
tiltedphoques/TiltedEvolution pull request #514
Opened 2022-09-23 23:15 UTC by NutyoPR

2022-09-24 09:17 UTC, Dragonisser commented
Dev not Master

2022-09-24 12:40 UTC, tomfull123 requested changes

2022-09-24 12:40 UTC, tomfull123 commented on Code/skyrim_ui/src/assets/i18n/pl.json
> +      "CONNECTION_LOST": "Stracono połączenie, próbujemy się podłączyć z powrotem. {{remainingReconnectionAttempt } pozostałych prób."
Looks like you're missing the second closing curly bracket from this line.

2022-09-25 19:04 UTC, tomfull123 approved these changes

2022-09-25 19:14 UTC, merged