[Draft] Feat/scripting 3.0
tiltedphoques/TiltedEvolution pull request #544
Opened 2022-12-14 16:04 UTC by Force67

You can now load scripts from the resources folder.

![image](https://user-images.githubusercontent.com/17651856/207646233-913e75d5-8644-4ace-928d-4200a37ec47a.png)

Script example:
![image](https://user-images.githubusercontent.com/17651856/207646304-e0c95cc1-8c17-46e1-aec1-56745afa52fe.png)

2023-04-02 15:29 UTC, RobbeBryssinck approved these changes

2023-04-02 15:32 UTC, yamashi requested changes

2023-04-02 15:32 UTC, yamashi commented on Code/server/GameServer.h
> +        int weeks;
Naming conventions

2023-04-02 15:32 UTC, yamashi commented on Code/server/GameServer.h
> +        int GetWeeks() const
You don't need getters for scripting

2023-04-10 17:41 UTC, maximegmd approved these changes

2023-04-11 18:12 UTC, merged