V1.6.0
tiltedphoques/TiltedEvolution pull request #618
Opened 2023-08-02 21:20 UTC by RobbeBryssinck

- Overhauled combat targeting system
- ESL mod syncing (Anniversary Edition support)
- Calendar sync and time progression
- Fixed crashes related to dragons
- Fixed wrong damage calculations
- Waypoint sync (blue markers on map)
- Fixed book reading bug
- Fixed SetTime command crash
- Fixed nightvision effect syncing
- Fixed rare memory leak
- Fixed quest start code (partially)

2023-08-03 11:17 UTC, Force67 requested changes

2023-08-03 11:17 UTC, Force67 commented on Code/encoding/Structs/TimeModel.cpp
not a big fan of having logic within a network packet for time model.

2023-08-03 11:17 UTC, Force67 commented on Code/encoding/Messages/ServerTimeSettings.cpp
Pls fix formatting

2023-08-03 11:17 UTC, Force67 commented
+ Fix linux

2023-08-08 07:21 UTC, Force67 approved these changes

2023-08-08 07:47 UTC, maximegmd approved these changes

2023-08-08 07:48 UTC, merged